theme="polymer"
baseurl = "https://b.tflare.com/"
#languageCode = "ja-jp"
title = "Hiroyuki Abeの投資日記"
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = "Copyright (c) 2018 - 2020, Hiroyuki Abeの投資日記"
canonifyurls = true
#publishdir = "docs"
#disqusShortname = "http-d-tflare-com.disqus.com" # optional

[params]
  author = "hiroyuki_t"
  photo = "images/photo.png" # optional
  profile = "images/profile.png" # optional
  cover = "images/cover.png" # optional
  twitter = "takibouyou64" # optional
  github = "tflare" # optional
